### ISSUE TITLE
Create Website Docker container

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#260]
A "full" setup of the website now involves postgres, celery, redis, recaptcha, plus a host of env variables and sqlalchemy migrations. 

@micahalcorn and I have basically given up on trying to run it all locally and started resorting to the very slow process of testing everything on sample heroku deploys. 

Much better would be to make a container, like [`origin-box`](https://github.com/OriginProtocol/origin-box), that has all the components pre-configured to work.

**Comment by micahalcorn** [comment]
@tomlinton did you want to explore this?

**Comment by tomlinton** [comment]
Yep, can do!

**Comment by tomlinton** [comment]
This is done in the [compose branch](https://github.com/OriginProtocol/origin-box/tree/compose) of origin-box. If you just clone it and run `/install.sh -e origin-website` you should be away. Come and yell at me on Discord if it doesn't work. :grimacing: 

I ran into a few issues with origin-website, it looks like the `.env` file isn't actually read for the configuration (perhaps people are using something like autoenv to do this on their machines). I put a few workarounds in origin-box but it means some settings reside in the docker files rather than the env files which could be confusing. I'll raise issue(s) on origin-website or fix it myself soon.

We should probably leave this issue open though in case we don't end up using the compose branch of origin-box.

**Comment by joshfraser** [comment]
I'm confused. What makes you think the .env is not being used? It should be.

**Comment by joshfraser** [comment]
Thanks for your work on this btw!

**Comment by tomlinton** [comment]
@joshfraser my mistake, it is! I had an error in the mounting of the .env file in origin-box.

**Comment by tomlinton** [comment]
Closed by [#29](https://github.com/OriginProtocol/origin-box/pull/29) on origin-box.
